[@Icons]

[*Stock]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *Stock command set-ini-val
refresh-return
back

[*EmuMMC]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *EmuMMC command set-ini-val
refresh-return
back

[*SysMMC]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *SysMMC command set-ini-val
refresh-return
back

[*Android]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *Android command set-ini-val
refresh-return
back

[*Ubuntu]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *Ubuntu command set-ini-val
refresh-return
back

[*Linux]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *Linux command set-ini-val
refresh-return
back

[*Lakka]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini *Lakka command set-ini-val
refresh-return
back

[*Lockpick RCM]
;mode=option
;mini=true
ini_file_source /bootloader/hekate_ipl.ini
filter config
set-footer {ini_file_source(*)}
set-ini-val ./config.ini '*Lockpick RCM' command set-ini-val
refresh-return
back



[Reset Configs]

[Reset Configs]
remove-ini-section ./config.ini *Stock
remove-ini-section ./config.ini *EmuMMC
remove-ini-section ./config.ini *SysMMC
remove-ini-section ./config.ini *Android
remove-ini-section ./config.ini *Ubuntu
remove-ini-section ./config.ini *Linux
remove-ini-section ./config.ini *Lakka
remove-ini-section ./config.ini '*Lockpick RCM'
refresh-to *Stock