[@Icons Advanced]

[*Stock ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Stock,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Stock,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Stock,command)},set-ini-val,notify-now,pass)}' notify-now 'Setup icon first' 20 left word 2250 Stock true
'{if_==({ini_file(*Stock,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*EmuMMC ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*EmuMMC,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*EmuMMC,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*EmuMMC,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 EmuMMC true
'{if_==({ini_file(*EmuMMC,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*SysMMC ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*SysMMC,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*SysMMC,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*SysMMC,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 SysMMC true
'{if_==({ini_file(*SysMMC,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*Android ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Android,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Android,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Android,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 Android true
'{if_==({ini_file(*Android,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*Ubuntu ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Ubuntu,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Ubuntu,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Ubuntu,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 Ubuntu true
'{if_==({ini_file(*Ubuntu,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*Linux ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Linux,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Linux,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Linux,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 Linux true
'{if_==({ini_file(*Linux,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*Lakka ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Lakka,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Lakka,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Lakka,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 Lakka true
'{if_==({ini_file(*Lakka,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back

[*Lockpick RCM ]
;mode=option
;mini=true
file_source '/switch/.packages/AIO Customizer/icon/*.bmp'
ini_file ./config.ini
'{if_==({ini_file(*Lockpick RCM,command)},set-ini-val,set-ini-val,pass)}' /bootloader/hekate_ipl.ini '{ini_file(*Lockpick RCM,footer)}' icon '/switch/.packages/AIO Customizer/icon/{file_name}.bmp'
'{if_!=({ini_file(*Lockpick RCM,command)},set-ini-val,notify-now,pass)}' 'Setup icon first' 20 left word 2250 'Lockpick RCM' true
'{if_==({ini_file(*Lockpick RCM,command)},set-ini-val,set-footer,pass)}' {file_name}
refresh-return
back



[Reset configs ]

[Reset configs ]
ini_file ./config.ini
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Stock,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*EmuMMC,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*SysMMC,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Android,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Ubuntu,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Linux,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Lakka,footer)}' icon
remove-ini-key /bootloader/hekate_ipl.ini '{ini_file(*Lockpick RCM,footer)}' icon
remove-ini-key ./config.ini '*Stock ' footer
remove-ini-key ./config.ini '*EmuMMC ' footer
remove-ini-key ./config.ini '*SysMMC ' footer
remove-ini-key ./config.ini '*Android ' footer
remove-ini-key ./config.ini '*Ubuntu ' footer
remove-ini-key ./config.ini '*Linux ' footer
remove-ini-key ./config.ini '*Lakka ' footer
remove-ini-key ./config.ini '*Lockpick RCM ' footer
refresh-to '*Stock '
