[Overlays]

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Horizon-OC'=''
'{if_!null({ovl_version(/switch/.overlays/horizon-oc-overlay.ovl)},Current: {ovl_version(/switch/.overlays/horizon-oc-overlay.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,Horizon-OC)}'

[Download Mode]
;mode=toggle?off
;mini=true
on:
   set-ini-val ./config.ini 'Download Mode' extensions on
   refresh-to 'Download Mode'
off:
   set-ini-val ./config.ini 'Download Mode' extensions off
   refresh-to 'Download Mode'

[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
ini_file ./config.ini
'Download Mode'='{if_!=({ini_file(Download Mode,extensions)},on,Horizon-OC,Horizon-OC + Extensions)}'

[Download Horizon-OC]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now '{if_!=({ini_file(Download Mode,extensions)},on,Updating to Horizon-OC {ini_file(Overlays Release Info,Horizon-OC)} press {R} to stop,Updating to Horizon-OC + Extensions {ini_file(Overlays Release Info,Horizon-OC)} press {R} to stop)}' 20 left word 2250 'Horizon-OC' true
download https://api.github.com/repos/Horizon-OC/Horizon-OC/releases?per_page=1 /config/ultrahand/downloads/horizon-oc.json
json_file /config/ultrahand/downloads/horizon-oc.json
'{if_!=({ini_file(Download Mode,extensions)},on,download,pass)}' {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/
'{if_==({ini_file(Download Mode,extensions)},on,download,pass)}' {json_file(0,assets,1,browser_download_url)} /config/ultrahand/downloads/
unzip '/config/ultrahand/downloads/{if_!=({ini_file(Download Mode,extensions)},on,dist.zip,dist_ext.zip)}' /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,Horizon-OC)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 'Horizon-OC' true
delete /config/ultrahand/downloads/*
refresh-to 'Download Horizon-OC'

[Open Horizon-OC]
;mini=true
try:
path_exists /switch/.overlays/horizon-oc-overlay.ovl
open /switch/.overlays/horizon-oc-overlay.ovl

try:
!path_exists /switch/.overlays/horizon-oc-overlay.ovl
notify-now 'Module not installed' 20 left word 2250 'Horizon-OC' true 

[Open Horizon-OC-Monitor]
;mini=true
try:
path_exists /switch/.overlays/Horizon-OC-Monitor.ovl
open /switch/.overlays/Horizon-OC-Monitor.ovl

try:
!path_exists /switch/.overlays/Horizon-OC-Monitor.ovl
notify-now 'Module not installed' 20 left word 2250 'Horizon-OC-Monitor' true 


[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'QuickNTP'=''
'{if_!null({ovl_version(/switch/.overlays/QuickNTP.ovl)},Current: {ovl_version(/switch/.overlays/QuickNTP.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,QuickNTP)}'

[Download QuickNTP]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,QuickNTP)} press {R} to stop' 20 left word 2250 QuickNTP true
download https://api.github.com/repos/ppkantorski/QuickNTP/releases?per_page=1 /config/ultrahand/downloads/quick_ntp.json
json_file /config/ultrahand/downloads/quick_ntp.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,QuickNTP)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 QuickNTP true
delete /config/ultrahand/downloads/*
refresh-to 'Download QuickNTP'

[Open QuickNTP]
;mini=true
try:
path_exists /switch/.overlays/QuickNTP.ovl
open /switch/.overlays/QuickNTP.ovl

try:
!path_exists /switch/.overlays/QuickNTP.ovl
notify-now 'Module not installed' 20 left word 2250 QuickNTP true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Tetris'=''
'{if_!null({ovl_version(/switch/.overlays/tetris.ovl)},Current: {ovl_version(/switch/.overlays/tetris.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,Tetris)}'

[Download Tetris]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,Tetris)} press {R} to stop' 20 left word 2250 Tetris true
download https://api.github.com/repos/ppkantorski/Tetris-Overlay/releases?per_page=1 /config/ultrahand/downloads/tetris.json
json_file /config/ultrahand/downloads/tetris.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,Tetris)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Tetris true
delete /config/ultrahand/downloads/*
refresh-to 'Download Tetris'

[Open Tetris]
;mini=true
try:
path_exists /switch/.overlays/tetris.ovl
open /switch/.overlays/tetris.ovl

try:
!path_exists /switch/.overlays/tetris.ovl
notify-now 'Module not installed' 20 left word 2250 Tetris true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'OvlSysmodules'=''
'{if_!null({ovl_version(/switch/.overlays/ovlSysmodules.ovl)},Current: {ovl_version(/switch/.overlays/ovlSysmodules.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,OvlSysmodules)}'

[Download OvlSysmodules]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,OvlSysmodules)} press {R} to stop' 20 left word 2250 OvlSysmodules true
download https://api.github.com/repos/ppkantorski/ovl-sysmodules/releases?per_page=1 /config/ultrahand/downloads/ovlSysmodules.json
json_file /config/ultrahand/downloads/ovlSysmodules.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,OvlSysmodules)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 OvlSysmodules true
delete /config/ultrahand/downloads/*
refresh-to 'Download OvlSysmodules'

[Open OvlSysmodules]
;mini=true
try:
path_exists /switch/.overlays/ovlSysmodules.ovl
open /switch/.overlays/ovlSysmodules.ovl

try:
!path_exists /switch/.overlays/ovlSysmodules.ovl
notify-now 'Module not installed' 20 left word 2250 OvlSysmodules true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Status-Monitor'=''
'{if_!null({ovl_version(/switch/.overlays/Status-Monitor-Overlay.ovl)},Current: {ovl_version(/switch/.overlays/Status-Monitor-Overlay.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,Status-Monitor)}'

[Download Status-Monitor]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,Status-Monitor)} press {R} to stop' 20 left word 2250 'Status-Monitor' true
download https://api.github.com/repos/ppkantorski/Status-Monitor-Overlay/releases?per_page=1 /config/ultrahand/downloads/status-monitor-overlay.json
json_file /config/ultrahand/downloads/status-monitor-overlay.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,Status-Monitor)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 'Status-Monitor' true
delete /config/ultrahand/downloads/*
refresh-to 'Download Status-Monitor'

[Open Status-Monitor]
;mini=true
try:
path_exists /switch/.overlays/Status-Monitor-Overlay.ovl
open /switch/.overlays/Status-Monitor-Overlay.ovl

try:
!path_exists /switch/.overlays/Status-Monitor-Overlay.ovl
notify-now 'Module not installed' 20 left word 2250 'Status-Monitor' true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'FPSLocker'=''
'{if_!null({ovl_version(/switch/.overlays/FPSLocker.ovl)},Current: {ovl_version(/switch/.overlays/FPSLocker.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,FPSLocker)}'

[Download FPSLocker]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,FPSLocker)} press {R} to stop' 20 left word 2250 FPSLocker true
download https://api.github.com/repos/ppkantorski/FPSLocker/releases?per_page=1 /config/ultrahand/downloads/fpsLocker.json
json_file /config/ultrahand/downloads/fpsLocker.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,FPSLocker)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 FPSLocker true
delete /config/ultrahand/downloads/*
refresh-to 'Download FPSLocker'

[Open FPSLocker]
;mini=true
try:
path_exists /switch/.overlays/FPSLocker.ovl
open /switch/.overlays/FPSLocker.ovl

try:
!path_exists /switch/.overlays/FPSLocker.ovl
notify-now 'Module not installed' 20 left word 2250 FPSLocker true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'ReverseNX-RT'=''
'{if_!null({ovl_version(/switch/.overlays/ReverseNX-RT-ovl.ovl)},Current: {ovl_version(/switch/.overlays/ReverseNX-RT-ovl.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,ReverseNX-RT)}'

[Download ReverseNX-RT]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,ReverseNX-RT)} press {R} to stop' 20 left word 2250 ReverseNX-RT true
download https://api.github.com/repos/ppkantorski/ReverseNX-RT/releases?per_page=1 /config/ultrahand/downloads/reversenx-rt.json
json_file /config/ultrahand/downloads/reversenx-rt.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,ReverseNX-RT)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 ReverseNX-RT true
delete /config/ultrahand/downloads/*
refresh-to 'Download ReverseNX-RT'

[Open ReverseNX-RT]
;mini=true
try:
path_exists /switch/.overlays/ReverseNX-RT-ovl.ovl
open /switch/.overlays/ReverseNX-RT-ovl.ovl

try:
!path_exists /switch/.overlays/ReverseNX-RT-ovl.ovl
notify-now 'Module not installed' 20 left word 2250 ReverseNX-RT true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Fizeau'=''
'{if_!null({ovl_version(/switch/.overlays/Fizeau.ovl)},Current: {ovl_version(/switch/.overlays/Fizeau.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,Fizeau)}'

[Download Fizeau]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,Fizeau)} press {R} to stop' 20 left word 2250 Fizeau true
download https://api.github.com/repos/ppkantorski/Fizeau/releases?per_page=1 /config/ultrahand/downloads/fizeau.json
json_file /config/ultrahand/downloads/fizeau.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,Fizeau)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Fizeau true
delete /config/ultrahand/downloads/*
refresh-to 'Download Fizeau'

[Open Fizeau]
;mini=true
try:
path_exists /switch/.overlays/Fizeau.ovl
open /switch/.overlays/Fizeau.ovl

try:
!path_exists /switch/.overlays/Fizeau.ovl
notify-now 'Module not installed' 20 left word 2250 Fizeau true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Sys-dvr'=''
'{if_!null({ovl_version(/switch/.overlays/sysdvr-overlay.ovl)},Current: {ovl_version(/switch/.overlays/sysdvr-overlay.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,Sys-dvr)}'

[Download Sys-dvr]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,Sys-dvr)} press {R} to stop' 20 left word 2250 'Sys-dvr' true
download https://api.github.com/repos/ppkantorski/sysdvr-overlay/releases?per_page=1 /config/ultrahand/downloads/sysdvr-overlay.json
json_file /config/ultrahand/downloads/sysdvr-overlay.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,Sys-dvr)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 'Sys-dvr' true
delete /config/ultrahand/downloads/*
refresh-to 'Download Sys-dvr'

[Open Sys-dvr]
;mini=true
try:
path_exists /switch/.overlays/sysdvr-overlay.ovl
open /switch/.overlays/sysdvr-overlay.ovl

try:
!path_exists /switch/.overlays/sysdvr-overlay.ovl
notify-now 'Module not installed' 20 left word 2250 'Sys-dvr' true 



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'NX-FanControl'=''
'{if_!null({ovl_version(/switch/.overlays/NX-FanControl.ovl)},Current: {ovl_version(/switch/.overlays/NX-FanControl.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Overlays Release Info,NX-FanControl)}'

[Download NX-FanControl]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Overlays Release Info,NX-FanControl)} press {R} to stop' 20 left word 2250 NX-FanControl true
download https://api.github.com/repos/ppkantorski/NX-FanControl/releases?per_page=1 /config/ultrahand/downloads/nx-fancontrol.json
json_file /config/ultrahand/downloads/nx-fancontrol.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Overlays Release Info,NX-FanControl)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 NX-FanControl true
delete /config/ultrahand/downloads/*
refresh-to 'Download NX-FanControl'

[Open NX-FanControl]
;mini=true
try:
path_exists /switch/.overlays/NX-FanControl.ovl
open /switch/.overlays/NX-FanControl.ovl

try:
!path_exists /switch/.overlays/NX-FanControl.ovl
notify-now 'Module not installed' 20 left word 2250 NX-FanControl true 