[Wallpaper]
ini_file '/switch/.packages/AIO Customizer/ini/theme customization/config.ini'
delete '/switch/.packages/AIO Customizer/wallpaper/{ini_file(*Wallpaper,footer)}.rgba'


[Disable Wallpaper]
;mini=true
ini_file '/switch/.packages/AIO Customizer/ini/theme customization/config.ini'
move /config/ultrahand/wallpaper.rgba '/switch/.packages/AIO Customizer/wallpaper/{ini_file(*Wallpaper,footer)}.rgba'
delete '/switch/.packages/AIO Customizer/wallpaper/Disabled.rgba'
remove-ini-key '/switch/.packages/AIO Customizer/ini/theme customization/config.ini' *Wallpaper footer
refresh wallpaper


[Cleanup]
delete '/switch/.packages/AIO Customizer/preset/default_preset/'
