[@Music]

[App Store Music]

[Disable App Store Music]
;mini=true
ini_file ./config.ini
'{if_==({ini_file(*App Store Music,footer)},Disabled,del,move)}' /switch/appstore/background.mp3 '/switch/.packages/AIO Customizer/music/appstore/{ini_file(*App Store Music,footer)}.mp3'
remove-ini-key ./config.ini '*App Store Music' footer
refresh-to 'Disable App Store Music'


[*App Store Music]
;mini=true
;mode=option
;footer=Disabled
ini_file ./config.ini
file_source '/switch/.packages/AIO Customizer/music/appstore/*.mp3'
'{if_==({ini_file(*App Store Music,footer)},Disabled,pass,move)}' /switch/appstore/background.mp3 '/switch/.packages/AIO Customizer/music/appstore/{ini_file(*App Store Music,footer)}.mp3'
move {file_source} /switch/appstore/background.mp3
set-footer {file_name}
refresh-return
back


[Downlaod HB App Store]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Downloading press {R} to stop' 20 left word 2250 'HB App Store' true
download https://api.github.com/repos/fortheusers/hb-appstore/releases?per_page=1 /config/ultrahand/downloads/hb-apptore-api.json
json_file /config/ultrahand/downloads/hb-apptore-api.json
download {json_file(0,assets,0,browser_download_url)} /switch/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Downloaded, took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 'HB App Store' true
delete /config/ultrahand/downloads/*



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
'Sphaira Music' =''


[Disable Sphaira Music]
;mini=true
ini_file ./config.ini
'{if_==({ini_file(*Sphaira Music,footer)},Disabled,del,move)}' /switch/sphaira/background.mp3 '/switch/.packages/AIO Customizer/music/sphaira/{ini_file(*Sphaira Music,footer)}.mp3'
remove-ini-key ./config.ini '*Sphaira Music' footer
refresh-to 'Disable Sphaira Music'


[*Sphaira Music]
;mini=true
;mode=option
;footer=Disabled
ini_file ./config.ini
file_source '/switch/.packages/AIO Customizer/music/sphaira/*.mp3'
set-ini-val /config/sphaira/config.ini config default_music /switch/sphaira/background.mp3
'{if_==({ini_file(*Sphaira Music,footer)},Disabled,pass,move)}' /switch/sphaira/background.mp3 '/switch/.packages/AIO Customizer/music/sphaira/{ini_file(*Sphaira Music,footer)}.mp3'
move {file_source} /switch/sphaira/background.mp3
set-footer {file_name}
refresh-return
back

[Downlaod Sphaira]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Downloading press {R} to stop' 20 left word 2250 Sphaira true
download https://api.github.com/repos/ITotalJustice/sphaira/releases?per_page=1 /config/ultrahand/downloads/sphaira-api.json
json_file /config/ultrahand/downloads/sphaira-api.json
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/sphaira.zip
notify-now 'Extracting' 20 left word 2250 Sphaira true
unzip /config/ultrahand/downloads/sphaira.zip /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Downloaded, took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Sphaira true
delete /config/ultrahand/downloads/*



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
'Sys-Tune Music' =''


[Disable Home Menu Music]
;mini=true
ini_file ./config.ini
module stop 4200000000000000
'{if_==({ini_file(*Home Menu Music,footer)},Disabled,del,move)}' '/config/sys-tune/background.mp3' '/switch/.packages/AIO Customizer/music/sys-tune/{ini_file(*Home Menu Music,footer)}.mp3'
remove-ini-key /config/sys-tune/config.ini config load_path
remove-ini-key ./config.ini '*Home Menu Music' footer
module start 4200000000000000
refresh-to 'Disable Home Menu Music'


[*Home Menu Music]
;mini=true
;mode=option
;footer=Disabled
ini_file ./config.ini
file_source '/switch/.packages/AIO Customizer/music/sys-tune/*.mp3'
module stop 4200000000000000
'{if_==({ini_file(*Home Menu Music,footer)},Disabled,pass,move)}' '/config/sys-tune/background.mp3' '/switch/.packages/AIO Customizer/music/sys-tune/{ini_file(*Home Menu Music,footer)}.mp3'
move {file_source} /config/sys-tune/background.mp3
set-ini-val /config/sys-tune/config.ini config load_path '/config/sys-tune/background.mp3'
set-footer {file_name}
module start 4200000000000000
refresh-return
back

[Gap]
;mode=table
;background=false
;gap=10

[Header]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {ovl_version(/switch/.overlays/sys-tune-overlay.ovl)}'='Latest: {ini_file(Release Info,Sys-tune)}'

[Gap]
;mode=table
;background=false
;gap=5

[Downlaod Sys-Tune]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Release Info,Sys-tune)} press {R} to stop' 20 left word 2250 Sys-tune true
download https://api.github.com/repos/ppkantorski/sys-tune/releases?per_page=1 /config/ultrahand/downloads/sys-tune.json
json_file /config/ultrahand/downloads/sys-tune.json
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/sys-tune.zip
notify-now 'Extracting' 20 left word 2250 Sys-Tune true
unzip /config/ultrahand/downloads/sys-tune.zip /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Release Info,Sys-tune)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Sys-tune true
delete /config/ultrahand/downloads/*


[Open Sys-Tune]
;mini=true
try:
module_exists 4200000000000000
open /switch/.overlays/sys-tune-overlay.ovl

try:
!module_exists 4200000000000000
notify-now 'Module not installed' 20 left word 2250 Sys-Tune true 