[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'QuickNTP'=''
'{if_!null({ovl_version(/switch/.overlays/QuickNTP.ovl)},Current: {ovl_version(/switch/.overlays/QuickNTP.ovl)},{INFO_SYMBOL} Overlay is not installed!)}'='Latest: {ini_file(Release Info,QuickNTP)}'


[Download QuickNTP]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
notify-now 'Updating to {ini_file(Release Info,QuickNTP)} press {R} to stop' 20 left word 2250 QuickNTP true
download https://api.github.com/repos/ppkantorski/QuickNTP/releases?per_page=1 /config/ultrahand/downloads/quick_ntp.json
json_file /config/ultrahand/downloads/quick_ntp.json
download {json_file(0,assets,0,browser_download_url)} /switch/.overlays/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Release Info,QuickNTP)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 QuickNTP true
delete /config/ultrahand/downloads/*
refresh-to 'Download QuickNTP'

[Open QuickNTP]
;mini=true
try:
path_exists /switch/.overlays/QuickNTP.ovl
open /switch/.overlays/QuickNTP.ovl

try:
!path_exists /switch/.overlays/QuickNTP.ovl
notify-now 'Module not installed' 20 left word 2250 QuickNTP true 
