[@Updater]

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Updater' =''
'Current: {ini_file(Release Info,current_version)}'='Latest: {ini_file(Release Info,latest_version)}'


[AIO Customizer - Latest]
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/GordyMcGarka/Ultrahand-Customizer/releases?per_page=1 /config/ultrahand/downloads/aio-customizer-api.json
json_file /config/ultrahand/downloads/aio-customizer-api.json
notify-now 'Updating to {ini_file(Release Info,latest_version)} press {R} to stop' 20 left word 2250 'AIO Customizer' true
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/aio-customizer.zip
notify-now 'Extracting' 20 left word 2250 'AIO Customizer' true
unzip /config/ultrahand/downloads/aio-customizer.zip /switch/.packages/
exec Backup
exec 'Current Release'
exec 'Release Info'
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Release Info,latest_version)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 'AIO Customizer' true 
delete /config/ultrahand/downloads/*
refresh-to 'AIO Customizer'



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
'Firmware' =''


[Update ALL - Latest]
try:
exec 'Atmosphere - Latest' ./updater_cleanup.ini
exec 'Firmware - Latest' ./updater_cleanup.ini
exec 'Hekate - Latest' ./updater_cleanup.ini
exec 'Sys-Patch - Latest' ./updater_cleanup.ini


[Gap]
;mode=table
;background=false
;gap=10

[Atmosphere Version]
;mode=table
;polling=false
;background=false
ini_file ./config.ini
'Current: {ams_version}'='Latest: {ini_file(Firmware Release Info,atmosphere)}'

[Gap]
;mode=table
;background=false
;gap=5

[Atmosphere - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/Atmosphere-NX/Atmosphere/releases?per_page=1 /config/ultrahand/downloads/atmosphere-api.json
json_file /config/ultrahand/downloads/atmosphere-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 20 left word 2250 Atmosphere true
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/atmosphere.zip
download {json_file(0,assets,1,browser_download_url)} '/firmware update/bootloader/payloads/'
notify-now 'Extracting' 20 left word 2250 Atmosphere true
unzip /config/ultrahand/downloads/atmosphere.zip /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Atmosphere true
delete /config/ultrahand/downloads/*
refresh-to 'Atmosphere'



[Gap]
;mode=table
;background=false
;gap=10

[Firmware Version]
;mode=table
;polling=false
;background=false
ini_file ./config.ini
'Current: {hos_version}'='Latest: {ini_file(Firmware Release Info,firmware)}'

[Gap]
;mode=table
;background=false
;gap=5

[Firmware - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/THZoria/NX_Firmware/releases?per_page=page=1 /config/ultrahand/downloads/firmware-api.json
json_file /config/ultrahand/downloads/firmware-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 20 left word 2250 Firmware true
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/firmware.zip
notify-now 'Extracting' 20 left word 2250 Firmware true
unzip /config/ultrahand/downloads/firmware.zip /Firmware_{json_file(0,tag_name)}/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Firmware true
delete /config/ultrahand/downloads/*
refresh-to 'Firmware'



[Gap]
;mode=table
;background=false
;gap=10

[Hekate Version]
;mode=table
;polling=false
;background=false
ini_file ./config.ini
'Current: {hekate_version}'='Latest: {ini_file(Firmware Release Info,hekate)}'

[Gap]
;mode=table
;background=false
;gap=5

[Hekate - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/CTCaer/hekate/releases?per_page=1 /config/ultrahand/downloads/hekate-api.json
json_file /config/ultrahand/downloads/hekate-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 20 left word 2250 Hekate true
download {json_file(0,assets,1,browser_download_url)} /config/ultrahand/downloads/hekate.zip
notify-now 'Extracting' 20 left word 2250 Hekate true
unzip /config/ultrahand/downloads/hekate.zip /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Hekate true
delete /config/ultrahand/downloads/*
refresh-to 'Hekate'



[Gap]
;mode=table
;background=false
;gap=10

[Sys-Patch Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {ovl_version(/switch/.overlays/sys-patch-overlay.ovl)}'='Latest: {ini_file(Firmware Release Info,sys-patch)}'

[Gap]
;mode=table
;background=false
;gap=5

[Sys-Patch - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/impeeza/sys-patch/releases?per_page=1 /config/ultrahand/downloads/sys-patch-api.json
json_file /config/ultrahand/downloads/sys-patch-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 20 left word 2250 Sys-Patch true
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/sys-patch.zip
notify-now 'Extracting' 20 left word 2250 Sys-Patch true
unzip /config/ultrahand/downloads/sys-patch.zip /
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Sys-Patch true
delete /config/ultrahand/downloads/*
refresh-to 'Sys-Patch'



[@Cleanup]

[Header]
;mode=table
;header_indent=true
;background=false
'Delete/Download Assets' =''

[*Boot Customization]
;mode=forwarder
package_source './boot.ini'



[*Musics Customization]
;mode=forwarder
package_source './music.ini'



[*Hekate & Wallpapers]
;mode=forwarder
package_source './h_w.ini'



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;header_indent=true
;background=false
;spacing=5
ini_file ./config.ini
'Update ALL Assets' =''
'Current: {ini_file(Assets Info,current_version)}'='Latest: {ini_file(Assets Info,latest_version)}'

[Update ALL Assets]
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
'{if_==({ini_file(Disable ALL Assets,status)},on,notify-now,pass)}' 'Disabling ALL Assets' 20 left word 2250 Assets true
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Bootlogo' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Bootsound' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Background' '/switch/.packages/AIO Customizer/ini/hekate customization/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable App Store Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Sphaira Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Home Menu Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{if_==({ini_file(Disable ALL Assets,status)},on,exec,pass)}' 'Disable Wallpaper' '/switch/.packages/AIO Customizer/ini/theme customization/boot_package.ini'
'{if_==({ini_file(Delete ALL Assets,status)},on,notify-now,pass)}' 'Deleting ALL Assets' 20 left word 2250 Assets true
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/background/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/bootlogo/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/bootsound/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/music/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/splashscreen/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/wallpaper/'
'{if_==({ini_file(Delete ALL Assets,status)},on,del,pass)}' '/switch/.packages/AIO Customizer/icon/'

notify-now 'Updating ALL Assets press {R} to stop' 20 left word 2250 Assets true
download https://github.com/GordyMcGarka/AIO-Customizer/releases/latest/download/assets.zip /config/ultrahand/downloads/
notify-now 'Extracting' 20 left word 2250 Assets true
unzip /config/ultrahand/downloads/assets.zip /
ini_file ./RELEASE.ini
set-ini-val ./config.ini 'Assets Info' current_version '{ini_file(Assets Info,current_version)}'
delete ./RELEASE.ini
ini_file ./config.ini
exec 'Boot Customization' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
exec 'Hekate Customization' '/switch/.packages/AIO Customizer/ini/hekate customization/boot_package.ini'
exec 'Wallpaper' '/switch/.packages/AIO Customizer/ini/theme customization/boot_package.ini'
exec 'Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
delete /config/ultrahand/downloads/*
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Assets Info,current_version)}, took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 20 left word 2250 Assets true
refresh-to 'Update ALL Assets'



[Gap]
;mode=table
;background=false
;gap=10

[Info]
;mode=table
;background=false
'When updating all assets{DOWN_ARROW}:'=''

[Gap]
;mode=table
;background=false
;gap=5

[Disable ALL Assets]
;mini=true
;mode=toggle?off
on:
    set-ini-val ./config.ini 'Disable ALL Assets' status on
off:
    set-ini-val ./config.ini 'Disable ALL Assets' status off


[Delete ALL Assets]
;mini=true
;mode=toggle?off
on:
    set-ini-val ./config.ini 'Delete ALL Assets' status on
off:
    set-ini-val ./config.ini 'Delete ALL Assets' status off