[Colors]

[Black]
;mini=true
;footer=■
;footer_color=000000
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 000000
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 000000
refresh-return
back


[White]
;mini=true
;footer=■
;footer_color=FFFFFF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FFFFFF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FFFFFF
refresh-return
back


[Gray]
;mini=true
;footer=■
;footer_color=888888
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 888888
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 888888
refresh-return
back


[Dark Gray]
;mini=true
;footer=■
;footer_color=444444
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 444444
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 444444
refresh-return
back


[Red]
;mini=true
;footer=■
;footer_color=FF0000
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FF0000
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FF0000
refresh-return
back


[Light Red]
;mini=true
;footer=■
;footer_color=FF5555
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FF5555
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FF5555
refresh-return
back


[Orange]
;mini=true
;footer=■
;footer_color=FF8800
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FF8800
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FF8800
refresh-return
back


[Light Orange]
;mini=true
;footer=■
;footer_color=FFBB66
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FFBB66
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FFBB66
refresh-return
back


[Yellow]
;mini=true
;footer=■
;footer_color=FFFF00
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FFFF00
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FFFF00
refresh-return
back


[Green]
;mini=true
;footer=■
;footer_color=00CC66
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 00CC66
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 00CC66
refresh-return
back


[Mint Green]
;mini=true
;footer=■
;footer_color=66FFAA
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 66FFAA
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 66FFAA
refresh-return
back


[Turquoise]
;mini=true
;footer=■
;footer_color=00CCAA
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 00CCAA
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 00CCAA
refresh-return
back


[Cyan]
;mini=true
;footer=■
;footer_color=00FFFF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 00FFFF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 00FFFF
refresh-return
back


[Sky Blue]
;mini=true
;footer=■
;footer_color=66CCFF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 66CCFF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 66CCFF
refresh-return
back


[Blue]
;mini=true
;footer=■
;footer_color=0066FF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 0066FF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 0066FF
refresh-return
back


[Dark Blue]
;mini=true
;footer=■
;footer_color=003399
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 003399
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 003399
refresh-return
back


[Purple]
;mini=true
;footer=■
;footer_color=9933FF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color 9933FF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color 9933FF
refresh-return
back


[Lavender]
;mini=true
;footer=■
;footer_color=CCAAFF
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color CCAAFF
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color CCAAFF
refresh-return
back


[Pink]
;mini=true
;footer=■
;footer_color=FF66CC
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FF66CC
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FF66CC
refresh-return
back


[Light Pink]
;mini=true
;footer=■
;footer_color=FFBBDD
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FFBBDD
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FFBBDD
refresh-return
back


[Magenta]
;mini=true
;footer=■
;footer_color=FF00AA
ini_file ./config.ini
set-ini-val ./config.ini '{ini_file(Smart Theme,color)}' color FF00AA
set-ini-val ./smart_theme.ini '{ini_file(Smart Theme,color)}' ;footer_color FF00AA
refresh-return
back