[@Main]

[General UI ]

[*General ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[bg color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bg_color {ini_file(theme,color)}
refresh theme

[bottom button color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_button_color {ini_file(theme,color)}
refresh theme

[click color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme click_color {ini_file(theme,color)}
refresh theme

[default overlay color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme default_overlay_color {ini_file(theme,color)}
refresh theme

[scrollbar color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_color {ini_file(theme,color)}
refresh theme

[scrollbar wall color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_wall_color {ini_file(theme,color)}
refresh theme

[selection bg color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme selection_bg_color {ini_file(theme,color)}
refresh theme

[star color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme star_color {ini_file(theme,color)}
refresh theme

[unfocused color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme unfocused_color {ini_file(theme,color)}
refresh theme

[s2 radio ring color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_radio_ring_color {ini_file(theme,color)}
refresh theme

[s2 radio selected color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_radio_selected_color {ini_file(theme,color)}
refresh theme

[s2 radio inprogress color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_radio_inprogress_color {ini_file(theme,color)}
refresh theme

[s2 radio_inner color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_radio_inner_color {ini_file(theme,color)}
refresh theme

[s2 toggle circle color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_toggle_circle_color {ini_file(theme,color)}
refresh theme

[s2 toggle on color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_toggle_on_color {ini_file(theme,color)}
refresh theme

[s2 toggle off color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_toggle_off_color {ini_file(theme,color)}
refresh theme



[*Separators]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[bottom separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_separator_color {ini_file(theme,color)}
refresh theme

[header separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme header_separator_color {ini_file(theme,color)}
refresh theme

[separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme separator_color {ini_file(theme,color)}
refresh theme

[text separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme text_separator_color {ini_file(theme,color)}
refresh theme

[top separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme top_separator_color {ini_file(theme,color)}
refresh theme



[*Table ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15



[table bg color ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme table_bg_color {ini_file(theme,color)}
refresh theme

[table border color]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme table_border_color {ini_file(theme,color)}
refresh theme

[s2 table border color 1 ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_1 {ini_file(theme,color)}
refresh theme

[s2 table border color_2 ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_2 {ini_file(theme,color)}
refresh theme

[s2 table border color 3 ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_3 {ini_file(theme,color)}
refresh theme

[s2 table border color 3 deep ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_3_deep {ini_file(theme,color)}
refresh theme

[s2 table border color 4 ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_4 {ini_file(theme,color)}
refresh theme

[s2 table border color 4 deep ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme s2_table_border_color_4_deep {ini_file(theme,color)}
refresh theme



[*Trackbars ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[trackbar empty color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_empty_color {ini_file(theme,color)}
refresh theme

[trackbar full color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_full_color {ini_file(theme,color)}
refresh theme

[trackbar slider border color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_border_color {ini_file(theme,color)}
refresh theme

[trackbar slider color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_color {ini_file(theme,color)}
refresh theme

[trackbar slider malleable color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_malleable_color {ini_file(theme,color)}
refresh theme