[Smart Theme]

[Apply Smart Theme]
exec 'Apply Smart Theme'
refresh theme

[Gap]
;mode=table
;background=false
;gap=15

[*Background]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Background Smart Theme'


[*Primary Text]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Primary Text Smart Theme'


[*Secondary Text]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Secondary Text Smart Theme'


[*Primary Accent]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Primary Accent Smart Theme'


[*Secondary Accent]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Secondary Accent Smart Theme'


[*Success]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Success Smart Theme'


[*Warning]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Warning Smart Theme'


[*Borders]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Borders Smart Theme'


[*Controls]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Controls Smart Theme'


[S2 Colors]

[*Color 1]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Color 1 Smart Theme'


[*Color 2]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Color 2 Smart Theme'


[*Color 3]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Color 3 Smart Theme'


[*Color 4]
;mode=forwarder
;mini=true
;footer=■
;footer_color=
package_source './color_sample.ini'
exec 'Color 4 Smart Theme'


[Transparency]

[Transparency Sample]
;mode=table
;background=true
;bg_color=000000
;border=false

[Gap]
;mode=table
;background=false
;gap=15

[Background Transparency]
;mode=trackbar
;unlocked=true
;min_value=0
;max_value=15
;on_every_tick=true
ini_file ./config.ini
set-ini-val ./config.ini 'Background Transparency' alpha {value}
set-ini-val /config/ultrahand/theme.ini theme table_bg_alpha {ini_file(theme,transparency)}
refresh theme


[Element Transparency]
;mode=trackbar
;unlocked=true
;min_value=0
;max_value=15
;on_every_tick=true
ini_file ./config.ini
set-ini-val ./config.ini 'Element Transparency' alpha {value}
set-ini-val /config/ultrahand/theme.ini theme table_bg_alpha {ini_file(theme,transparency)}
refresh theme