[@Main]

[Theme Customizer]

[*Smart Theme]
;mode=forwarder
package_source './smart_theme.ini'
exec 'Smart Theme'

[Gap]
;mode=table
;background=false
;gap=15

[Header]
;mode=table
;background=false
;header_indent=true
'Colors Options'=''

[*General UI]
;mode=forwarder
package_source './general_ui.ini'
exec Color
exec 'General UI'

[*Highlights & Logos]
;mode=forwarder
package_source './highlights&logos.ini'
exec Color
exec 'Highlights & Logos'


[*Text & Versions]
;mode=forwarder
package_source './text&versions.ini'
exec Color
exec 'Text & Version'


[*Widget]
;mode=forwarder
package_source './widget.ini'
exec Color
exec 'Widget'


[Gap]
;mode=table
;background=false
;gap=15

[Header]
;color=
;mode=table
;background=false
;header_indent=true
;polling=false
'Transparency'=''

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency



[@RGB]

[Theme Customizer]

[*Smart Theme]
;mode=forwarder
package_source './smart_theme.ini'

[Gap]
;mode=table
;background=false
;gap=15

[Header]
;color=
;mode=table
;background=false
;header_indent=true
;polling=false
'Colors Options RGB'=''

[*General UI RGB]
;mode=forwarder
package_source './general_ui_rgb.ini'
exec 'Color RGB'
exec 'General UI RGB'


[*Highlights & Logos RGB]
;mode=forwarder
package_source './highlights&logos_rgb.ini'
exec 'Color RGB'
exec 'Highlights & Logos RGB'


[*Text & Versions RGB]
;mode=forwarder
package_source './text&versions_rgb.ini'
exec 'Color RGB'
exec 'Text & Version RGB'


[*Widget RGB]
;mode=forwarder
package_source './widget_rgb.ini'
exec 'Color RGB'
exec 'Widget RGB'



[Gap]
;mode=table
;background=false
;gap=15

[Header]
;color=
;mode=table
;background=false
;header_indent=true
;polling=false
'Transparency'=''

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency