[@Main]

[Colors Options]

[*General UI]
;mode=forwarder
package_source './general_ui.ini'
exec Color


[*Highlights & Logos]
;mode=forwarder
package_source './highlights&logos.ini'
exec Color


[*Text & Versions]
;mode=forwarder
package_source './text&versions.ini'
exec Color


[*Widget]
;mode=forwarder
package_source './widget.ini'
exec Color


[Transparency]

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency



[@RGB]

[Colors Options]

[*General UI]
;mode=forwarder
package_source './general_ui_rgb.ini'
exec Color
exec 'General UI'


[*Highlights & Logos]
;mode=forwarder
package_source './highlights&logos_rgb.ini'
exec Color
exec 'Highlights & Logos'


[*Text & Versions]
;mode=forwarder
package_source './text&versions_rgb.ini'
exec Color
exec 'Text & Version'


[*Widget]
;mode=forwarder
package_source './widget_rgb.ini'
exec Color
exec 'Widget'


[Transparency]

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency