[@RGB]

[Widget]

[*Battery]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=15

[Color Sample]
;mode=table
;background=true
;border=false

[Gap]
;mode=table
;background=false
;gap=15

[battery charging color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_charging_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'battery charging color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'battery charging color '

[battery color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'battery color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'battery color '

[battery low color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_low_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'battery low color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'battery low color '


[*General]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=15

[Color Sample]
;mode=table
;background=true
;border=false

[Gap]
;mode=table
;background=false
;gap=15

[banner version text color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme banner_version_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'banner version text color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'banner version text color '

[clock color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme clock_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'clock color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'clock color '

[temperature color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme temperature_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'temperature color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'temperature color '

[widget backdrop color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_backdrop_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'widget backdrop color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'widget backdrop color '

[widget border color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_border_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'widget border color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'widget border color '

[s2 widget border color 1 ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_1 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 1 ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 1 '

[s2 widget border color 2 ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_2 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 2 ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 2 '

[s2 widget border color 3 ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_3 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 3 ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 3 '

[s2 widget border color 3 deep ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_3_deep '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 3 deep ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 3 deep '

[s2 widget border color 4 ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_4 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 4 ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 4 '

[s2 widget border color 4 deep ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_4_deep '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 's2 widget border color 4 deep ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 's2 widget border color 4 deep '

[*Ram]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=15

[Color Sample]
;mode=table
;background=true
;border=false

[Gap]
;mode=table
;background=false
;gap=15

[bad ram text color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bad_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'bad ram text color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'bad ram text color '

[healthy ram text color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme healthy_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'healthy ram text color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'healthy ram text color '

[neutral ram text color ]
;mini=true
;footer=■
;footer_color=
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme neutral_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-ini-val ./widget_rgb.ini 'neutral ram text color ' ;footer_color {ini_file(theme,color)}
refresh theme
refresh-to 'neutral ram text color '