[@RGB]

[Widget]

[*Battery]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[battery charging color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_charging_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'battery charging color'

[battery color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'battery color'

[battery low color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_low_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'battery low color'


[*General]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[banner version text color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme banner_version_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'banner version text color'

[clock color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme clock_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'clock color'

[temperature color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme temperature_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'temperature color'

[widget backdrop color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_backdrop_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'widget backdrop color'

[widget border color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_border_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'widget border color'

[s2 widget border color 1]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_1 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_1'

[s2 widget border color 2]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_2 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_2'

[s2 widget border color 3]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_3 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_3'

[s2 widget border color 3 deep]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_3_deep '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_3_deep'

[s2 widget border color 4]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_4 '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_4'

[s2 widget border color 4 deep]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme s2_widget_border_color_4_deep '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 's2_widget_border_color_4_deep'

[*RAM]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[bad ram text color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bad_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'bad ram text color'

[healthy ram text color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme healthy_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'healthy ram text color'

[neutral ram text color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme neutral_ram_text_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'neutral ram text color'